version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: fsw-barber-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5412251
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data: